spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5338/caldav
    username: user
    password: qwerty
  liquibase:
    change-log: classpath:/db/migration/master.xml
  jpa:
    properties:
      hibernate:
        order_insert: true
        jdbc:
          batch_size: '5000'
          show_sql: true
          format_sql: true
