version: "3.9"
services:
  postgres:
    container_name: caldav
    image: postgres
    environment:
      POSTGRES_DB: "caldav"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5338:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
